export const THEME_PRESETS = [
  "Animals",
  "Architecture",
  "Colors & Art",
  "Education",
  "Fashion & Clothing",
  "Food & Cooking",
  "Games & Toys",
  "Geography",
  "History",
  "Insects & Bugs",
  "Language & Words",
  "Law & Crime",
  "Literature & Books",
  "Mathematics",
  "Medicine & Health",
  "Money & Finance",
  "Mountains & Geology",
  "Movies & Film",
  "Music & Instruments",
  "Mythology",
  "Ocean & Sea",
  "Plants & Gardening",
  "Religion",
  "Science & Chemistry",
  "Space & Astronomy",
  "Sports",
  "Technology & Computers",
  "Transportation",
  "War & Military",
  "Weather & Climate",
] as const

export type ThemePreset = (typeof THEME_PRESETS)[number]
